.gitignore, docker-compose-prod.yml, docker-compose-test.yml
This adds the volume to keep track of the lucene indices.
=> Add volume for lucene indices

docker-compose-prod.yml, docker-compose-test.yml, mde-nginx/test/default.conf
=> Adjust deployments

codelists/terms_of_use.yaml, docker-compose-prod.yml, docker-compose-test.yml
This adds the codelists folder. It also adds the corresponding volume to the client.
=> Add codelists volume

docker-compose-prod.yml, docker-compose-test.yml
=> Add codelist mount for backend

.env.example, docker-compose-prod.yml
@KaiVolland Please review.
Take note that `.env` files need to be adapted.
=> Add csw env variables

docker-compose-prod.yml, docker-compose-test.yml
Update Client to version 3.0.1:
* send json repsonse in replace_variable interface ([fe0eccf](https://github.com/gdi-be/mde-client/commit/fe0eccfe7d2dbd9a6bba5ae5bc82c1e1a11aef48))
* fix build ([60abaa8](https://github.com/gdi-be/mde-client/commit/60abaa815dba145234186a645792b07204ebbe76))
* comments from readonly ([f39a994](https://github.com/gdi-be/mde-client/commit/f39a994fe3f7d846dc2e1b621b58d4dbbc050995))
* make value bindable in ServiceShortDescription ([315958b](https://github.com/gdi-be/mde-client/commit/315958bd73b01915620ee297eb3120a77a3ca909))
* update actions in MetadataCard ([8f8de34](https://github.com/gdi-be/mde-client/commit/8f8de345ee9ef70358310ca83b80320d6dd6eb7a))
* update binding of TextAreaInput ([2b902a5](https://github.com/gdi-be/mde-client/commit/2b902a50a51d0dafaf4 …
=> Update client to version 3.0.1

README.md, docker-compose-prod.yml, docker-compose-test.yml
=> Describe the steps necessary for AD access

codelists/README.md, codelists/field_labels.yaml
This adds the field labels required for https://github.com/gdi-be/mde-client/pull/67
=> Add field labels

docker-compose-prod.yml, docker-compose-test.yml, run-importer.sh
=> Update versions, add importer script

.client-env.example, docker-compose-prod.yml, docker-compose-test.yml
Please review @KaiVolland @hwbllmnn.
=> Update backend and client images

run-importer.sh
=> Add flag to assign users on import

run-importer.sh
=> Configure db url when using the importer

codelists/README.md, codelists/field_labels.yaml
Implement the new field configuration to enhance functionality.
=> Use new field configuration

codelists/field_labels.yaml, docker-compose-prod.yml, docker-compose-test.yml
Upgrade the mde-client to version 3.16.0 and adjust various field labels in the configuration to improve clarity and consistency.
=> Update mde-client version and modify field labels

docker-compose-prod.yml, docker-compose-test.yml
Upgrade the mde-client service to use version 3.17.0 in the Docker configuration.
=> Update mde-client to version 3.17.0

docker-compose-prod.yml, docker-compose-test.yml
=> Update client image

docker-compose-test.yml
=> Update test yaml with version from test system

INSTALLATION.md
=> Add installation docs

sytem-architecture.md
Introduce a new document detailing the system architecture, including descriptions of the main components and their responsibilities within the application. This documentation aims to enhance understanding of the modular structure and interactions between services.
=> Add system architecture documentation

codelists/help/clientMetadata/comments.md, codelists/help/config.yaml
Adds a help document for the comments panel.
=> Add configuration for comment help functionality
